/**
 * Central data model.
 *
 * Architectural rule (spec §60): three things are kept strictly separate.
 *
 *   1. GEOGRAPHIC DATA  — geometry + semantic attributes. Lives in this file.
 *                         Always WGS84 (EPSG:4326) lon/lat. Never projected on disk.
 *   2. CARTOGRAPHIC APPEARANCE — style classes in `StyleSheet`. Features reference a
 *                         style class by id and may carry a sparse override object.
 *   3. UI STATE         — current tool, selection, hover, zoom. Lives in `src/state/uiStore.ts`
 *                         and is deliberately NOT part of `MapProject`, so it is never
 *                         serialised into a project file.
 *
 * Everything here must stay JSON-serialisable: no Dates, no Maps, no class instances,
 * no functions. That is what makes autosave, undo patches and the .atfmap file format work.
 */

import type { Feature, MultiPolygon, Point, Polygon, LineString, MultiLineString } from 'geojson';

/** Stable identifier. Generated by `newId()` in `./ids`. */
export type UUID = string;

/** Hex colour, `#rrggbb` or `#rrggbbaa`. */
export type Color = string;

// ---------------------------------------------------------------------------
// Timeline (spec §30 — designed in now, driven by UI in Phase 4)
// ---------------------------------------------------------------------------

/**
 * Half-open year range: a feature exists when `start <= year < end`.
 * `null` means unbounded in that direction. Years are astronomical
 * (i.e. 0 is 1 BC, -1 is 2 BC), so ordinary numeric comparison works.
 */
export interface TimelineRange {
  start: number | null;
  end: number | null;
}

export interface TimelineSettings {
  enabled: boolean;
  currentYear: number;
  minYear: number;
  maxYear: number;
  /** Step of the timeline slider, in years. */
  step: number;
}

// ---------------------------------------------------------------------------
// Projections (spec §4)
// ---------------------------------------------------------------------------

export type ProjectionId =
  | 'EPSG:3857' // Web Mercator
  | 'EPSG:4326' // Equirectangular / plate carrée
  | 'ATF:ROBINSON'
  | 'ATF:WINKEL3'
  | 'ATF:NATURALEARTH'
  | 'ATF:LCC'
  | 'ATF:ALBERS'
  | 'ATF:ORTHOGRAPHIC'
  | 'ATF:MERCATOR'
  | (string & {}); // custom proj4 definitions get an arbitrary id

export interface ProjectionSettings {
  id: ProjectionId;
  /** Human-readable name shown in the status bar and project dialog. */
  name: string;
  /** proj4 definition string. Empty for the two EPSG codes OpenLayers ships with. */
  proj4: string;
  /** Extent in projected units, used to seed the OpenLayers view. */
  extent: [number, number, number, number] | null;
  /** `m` (metres) or `degrees`. Drives the scale bar and the coordinate readout. */
  units: 'm' | 'degrees';
}

// ---------------------------------------------------------------------------
// Styling (spec §8, §9, §40, §42, §45)
// ---------------------------------------------------------------------------

export type HatchKind =
  | 'none'
  | 'diagonal'
  | 'reverse-diagonal'
  | 'crosshatch'
  | 'dots'
  | 'vertical'
  | 'horizontal';

/**
 * A hatch fill. Rendered to a CanvasPattern for the live map and to an SVG
 * `<pattern>` on export, from this one definition — see `src/render/patterns.ts`.
 */
export interface HatchPattern {
  kind: HatchKind;
  /** Degrees, clockwise. Applied on top of the base angle implied by `kind`. */
  angle: number;
  /** Distance between strokes, in CSS px at 1:1 zoom. */
  spacing: number;
  thickness: number;
  color: Color;
  opacity: number;
}

export type DashKind = 'solid' | 'dashed' | 'dotted' | 'dash-dot' | 'double' | 'alternating';

export interface LineStyle {
  color: Color;
  width: number;
  opacity: number;
  dash: DashKind;
  /** Second stroke drawn underneath, used for `double` and casing effects. */
  casingColor: Color | null;
  casingWidth: number;
  lineCap: 'butt' | 'round' | 'square';
  lineJoin: 'miter' | 'round' | 'bevel';
}

export interface TerritoryStyle {
  fillColor: Color;
  fillOpacity: number;
  pattern: HatchPattern | null;
  /** Outline drawn around the territory itself. Border *hierarchy* (§8) is a
   *  separate concern handled by `BorderStyleKind` on derived border geometry. */
  outline: LineStyle;
}

export interface TextStyle {
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  italic: boolean;
  color: Color;
  opacity: number;
  /** Letter spacing in px. Country and ocean labels use extreme values (§42, §43). */
  tracking: number;
  /** Multiplier on font size. */
  lineHeight: number;
  transform: 'none' | 'uppercase' | 'lowercase' | 'capitalize';
  haloColor: Color | null;
  haloWidth: number;
  /** Stroke drawn on the glyph outline itself, distinct from the halo. */
  outlineColor: Color | null;
  outlineWidth: number;
  align: 'left' | 'center' | 'right';
}

export type SymbolShape =
  | 'circle'
  | 'filled-circle'
  | 'double-circle'
  | 'star'
  | 'square'
  | 'filled-square'
  | 'diamond'
  | 'triangle'
  | 'cross'
  | 'castle'
  | 'keep'
  | 'holy-site'
  | 'anchor'
  | 'battle'
  | 'ruins'
  | 'temple'
  | 'mountain'
  | 'factory'
  | 'airfield'
  | 'custom-svg';

export interface SymbolStyle {
  shape: SymbolShape;
  size: number;
  fillColor: Color;
  strokeColor: Color;
  strokeWidth: number;
  opacity: number;
  /** Raw SVG path data, used when `shape === 'custom-svg'`. Drawn in a 0..100 box. */
  customPath: string | null;
}

/** A named, reusable style (spec §40). Editing one updates every feature that uses it. */
export interface StyleClass<T> {
  id: UUID;
  name: string;
  /** Style classes cannot be deleted while built-in, to keep projects loadable. */
  builtin: boolean;
  style: T;
}

export interface StyleSheet {
  territory: Record<UUID, StyleClass<TerritoryStyle>>;
  line: Record<UUID, StyleClass<LineStyle>>;
  text: Record<UUID, StyleClass<TextStyle>>;
  symbol: Record<UUID, StyleClass<SymbolStyle>>;
}

// ---------------------------------------------------------------------------
// Layers (spec §19)
// ---------------------------------------------------------------------------

/**
 * What kind of content a layer holds. A layer only ever holds one kind, which is
 * what lets the renderer build one OpenLayers layer per map layer and keeps
 * z-ordering meaningful.
 */
export type LayerKind =
  | 'group'
  | 'ocean'
  | 'basemap'
  | 'territory'
  | 'border'
  | 'river'
  | 'road'
  | 'settlement'
  | 'label'
  | 'graticule'
  | 'reference-image';

export interface MapLayer {
  id: UUID;
  name: string;
  kind: LayerKind;
  /** `null` for top-level layers. Groups nest arbitrarily deep. */
  parentId: UUID | null;
  visible: boolean;
  locked: boolean;
  opacity: number;
  /** Collapsed state of a group in the layer tree. UI-ish, but worth persisting. */
  collapsed: boolean;
  /** Order among siblings, ascending = drawn first = underneath. */
  order: number;
}

// ---------------------------------------------------------------------------
// Political geography (spec §5, §7, §31)
// ---------------------------------------------------------------------------

export type PoliticalType =
  | 'empire'
  | 'kingdom'
  | 'grand-duchy'
  | 'duchy'
  | 'principality'
  | 'county'
  | 'republic'
  | 'city-state'
  | 'confederation'
  | 'tribal-confederacy'
  | 'bishopric'
  | 'theocracy'
  | 'march'
  | 'protectorate'
  | 'colony'
  | 'vassal'
  | 'autonomous-territory'
  | 'occupied-territory'
  | 'disputed-territory'
  | 'province'
  | 'district'
  | 'barony'
  | (string & {}); // custom types (§5) are just free strings

/**
 * How a territory is held, as opposed to what it is called (spec §7).
 *
 * `politicalType` is a *rank* — duchy, county, canton. This is the orthogonal
 * question of constitutional status, and the two genuinely are independent: the
 * County of Dubuque is a county by rank and a vassal by status, while the Canton
 * of Iowa is an ordinary member of the same confederation. Keeping them in one
 * field, as this used to, means the map cannot tell those two apart, and every
 * subdivision ends up drawn like an independent country.
 *
 * The renderer derives the fill, the border class, the label class and the
 * relationship subtitle from this one value, so changing a vassal to a sovereign
 * restyles it, redraws its frontier and drops it out of its old parent's union
 * without anything else being edited.
 */
export type PoliticalRelationship =
  | 'sovereign'
  /** An ordinary canton, province or state of the parent realm. */
  | 'constituent'
  | 'vassal'
  | 'autonomous-vassal'
  | 'tributary'
  | 'personal-union'
  | 'free-city'
  | 'march'
  | 'protectorate'
  | 'occupied'
  | 'disputed'
  | (string & {});

/**
 * How strongly a realm's members are drawn as part of it (spec §18).
 *
 * Scales the colour variation every relationship asks for, so one control takes
 * a map from "these are all one country" to "these are allies who happen to
 * share a border". `independent` switches inheritance off altogether.
 */
export type PoliticalCohesion = 'unified' | 'strong' | 'moderate' | 'loose' | 'independent';

/** Fields shared by every addressable thing on the map. */
export interface FeatureBase {
  id: UUID;
  layerId: UUID;
  name: string;
  notes: string;
  locked: boolean;
  hidden: boolean;
  timeline: TimelineRange;
}

export interface Territory extends FeatureBase {
  shortName: string;
  /** What it is called: empire, duchy, canton, county. Its *rank*. */
  politicalType: PoliticalType;
  /**
   * How it is held: sovereign, ordinary constituent, vassal, free city. Its
   * *status*, which is a separate question from its rank — see
   * `PoliticalRelationship`. Drives fill, border class and label class.
   */
  relationship: PoliticalRelationship;
  /**
   * Hierarchy (§7). Points at another Territory. An Empire has `parentId: null`;
   * its Kingdoms point at it; their Duchies point at the Kingdoms, and so on.
   * There is no depth limit — `depthOf()` in `src/model/hierarchy.ts` walks it.
   */
  parentId: UUID | null;
  /** Overlord for personal unions / vassalage that does not match the containment tree. */
  liegeId: UUID | null;
  /** Settlement id of the capital. */
  capitalId: UUID | null;
  geometry: Polygon | MultiPolygon;
  styleClassId: UUID;
  /** Sparse overrides on top of the style class (§40: "objects may override"). */
  styleOverrides: Partial<TerritoryStyle>;
  /**
   * When true the territory takes its fill from its parent, lightened by
   * `shadeStep` per level of depth (§7, §9).
   */
  inheritParentColor: boolean;
  /** Which border weight to draw around this territory (§8). */
  borderKind: BorderStyleKind;
  labelId: UUID | null;
}

export type BorderStyleKind =
  | 'international'
  | 'major-political'
  | 'subordinate'
  | 'provincial'
  | 'county'
  | 'disputed'
  | 'ceasefire'
  | 'historical'
  | (string & {});

// ---------------------------------------------------------------------------
// Settlements (spec §14)
// ---------------------------------------------------------------------------

export type SettlementType =
  | 'imperial-capital'
  | 'national-capital'
  | 'regional-capital'
  | 'city'
  | 'town'
  | 'village'
  | 'fortress'
  | 'port'
  | 'monastery'
  | 'ruins'
  | (string & {});

export interface Settlement extends FeatureBase {
  type: SettlementType;
  geometry: Point;
  population: number | null;
  /** Territory that owns it. */
  ownerId: UUID | null;
  styleClassId: UUID;
  styleOverrides: Partial<SymbolStyle>;
  labelId: UUID | null;
}

// ---------------------------------------------------------------------------
// Linear features — rivers, roads, decorative paths (spec §15, §16)
// ---------------------------------------------------------------------------

export type LinearKind =
  | 'river'
  | 'river-major'
  | 'canal'
  | 'road-major'
  | 'road-minor'
  | 'trade-route'
  | 'roman-road'
  | 'trail'
  | 'sea-route'
  | 'label-path' // invisible carrier for text-on-path (§12)
  | (string & {});

export interface LinearFeature extends FeatureBase {
  kind: LinearKind;
  geometry: LineString | MultiLineString;
  styleClassId: UUID;
  styleOverrides: Partial<LineStyle>;
  /** Rivers flow into other rivers; used for hierarchy and width tapering. */
  flowsIntoId: UUID | null;
  /** Chaikin smoothing iterations applied at render time, 0 = raw vertices. */
  smoothing: number;
  labelId: UUID | null;
}

// ---------------------------------------------------------------------------
// Labels (spec §10, §11, §12)
// ---------------------------------------------------------------------------

export type LabelKind =
  | 'country'
  | 'region'
  | 'city'
  | 'water'
  | 'ocean'
  | 'river'
  | 'mountain'
  | 'free';

export interface MapLabel extends FeatureBase {
  kind: LabelKind;
  text: string;
  /**
   * Anchor in WGS84. For attached labels this is recomputed when the owner moves,
   * unless `manualPosition` is set — that is the whole point of §11.
   */
  anchor: Point;
  /** Feature this label describes, if any. */
  attachedToId: UUID | null;
  /** True once the user has dragged the label; suppresses automatic placement. */
  manualPosition: boolean;
  /** Offset from the anchor in screen px, applied after projection. */
  offset: [number, number];
  /** Degrees, clockwise. */
  rotation: number;
  styleClassId: UUID;
  styleOverrides: Partial<TextStyle>;
  /** Id of a `LinearFeature` with `kind: 'label-path'` to run the text along (§12). */
  pathId: UUID | null;
  /** Exempt this label from collision checks (§13). */
  ignoreCollisions: boolean;
  /**
   * Draw at the style's own size whatever the zoom (§42).
   *
   * A territory's name is normally an inscription across the land: it is laid
   * out against the shape and then travels with the map, so it spans its realm
   * at every scale. That is wrong for a name you have placed and sized by hand —
   * a note, a title, a caption on one feature — which should stay the size you
   * set it. Setting this pins it.
   */
  fixedSize: boolean;
  /**
   * Bend the text along an arc (§10): 0 is a straight line, 1 arches it upwards
   * like a rainbow, -1 cups it downwards. A name set on a carrier path follows
   * the path instead and ignores this.
   */
  curve: number;
  /** Explicit line breaks the user typed (§10). */
  maxWidth: number | null;
}

// ---------------------------------------------------------------------------
// Basemap reference data
// ---------------------------------------------------------------------------

/**
 * A read-only real-world dataset shown underneath the political map. These are
 * *not* part of the editable document — they are a tracing/reference aid, and
 * `convertBasemapToTerritories()` is what turns a selection of them into real
 * editable `Territory` records (§3: "the user should not be forced to trace the
 * entire coastline of North America manually").
 */
export interface BasemapSource {
  id: string;
  name: string;
  /** URL under /data, or an object URL for user imports. */
  url: string;
  format: 'topojson' | 'geojson';
  /** TopoJSON object key to extract. */
  objectName?: string;
  role:
    | 'land' | 'elevation' | 'countries' | 'states' | 'counties'
    | 'lakes' | 'rivers' | 'roads' | 'places' | 'custom';
}

export interface BasemapLayerState {
  sourceId: string;
  visible: boolean;
  opacity: number;
}

// ---------------------------------------------------------------------------
// Project (spec §49)
// ---------------------------------------------------------------------------

export interface ProjectMeta {
  title: string;
  subtitle: string;
  author: string;
  /** Free text — "in the year 1453". Not parsed. */
  dateLine: string;
  notes: string;
  createdAt: string; // ISO
  modifiedAt: string; // ISO
}

export interface SavedView {
  center: [number, number]; // WGS84
  /** OpenLayers zoom level. */
  zoom: number;
  rotation: number;
}

export interface MapProject {
  /** Bumped whenever the on-disk shape changes; `migrate()` upgrades old files. */
  schemaVersion: number;
  id: UUID;
  meta: ProjectMeta;
  projection: ProjectionSettings;
  view: SavedView;
  /**
   * The area of the world this map is about, as WGS84 [w, s, e, n] — or null
   * for "everywhere", which is the default.
   *
   * A map of the Americas has no use for Asian coastlines or seven thousand
   * European cities: they cost time to project and draw, they widen the view so
   * far that the subject is a thumbnail, and they are visual noise in every
   * export. Setting this crops the reference geography, and stops the view
   * panning or zooming out past the region — the map behaves like a sheet of
   * paper of a definite size rather than a window onto the whole globe.
   *
   * It bounds nothing about the *document*: territories, labels and settlements
   * outside it are still drawn, still exported and still editable. This is a
   * statement about what the reference data is for, not a fence around your work.
   */
  workingExtent: [number, number, number, number] | null;
  layers: Record<UUID, MapLayer>;
  territories: Record<UUID, Territory>;
  settlements: Record<UUID, Settlement>;
  linearFeatures: Record<UUID, LinearFeature>;
  labels: Record<UUID, MapLabel>;
  styles: StyleSheet;
  timeline: TimelineSettings;
  basemap: BasemapLayerState[];
  /**
   * How strongly members of a realm are drawn as part of it (spec §18). One
   * control over the whole map, because "how unified do these look" is a
   * decision about the plate, not about any one territory.
   */
  politicalCohesion: PoliticalCohesion;
  /** Colour applied behind everything — the ocean (§17). */
  oceanColor: Color;
  landColor: Color;
  legend: LegendSettings;
  compass: CompassSettings;
  /**
   * Print every realm's name, whatever the zoom (spec §28).
   *
   * Off, the map thins its names the way an atlas does: a realm is named on the
   * plate that shows the realm, and what is inside it waits for a closer one, so
   * a hemisphere reads as thirty realms rather than four hundred overlapping
   * halos. On, nothing is held back — which is what you want when the map *is*
   * the index, or when you are working and need to see the name of the thing you
   * are editing however far out you happen to be.
   */
  nameEverything: boolean;
  /**
   * Reference places the map has struck out, as `"lon,lat"` to three decimals.
   *
   * The places layer is reference geography, not part of the document, so there
   * is nothing to select and nothing to delete — but a city of your own sits on
   * top of one often enough that deleting the city uncovers a dot you thought
   * you had just removed. Deleting a settlement records where it stood here, and
   * the reference layer stops drawing whatever was underneath it. Nothing else
   * writes to this: reference geography is otherwise never edited.
   */
  dismissedPlaces: string[];
}

/** Where a piece of map furniture sits inside the frame. */
export type FurniturePosition = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

/**
 * One row of the legend (§26).
 *
 * A row names a style class rather than carrying its own appearance, so the
 * swatch is drawn by the same code that draws the map. Change the Sovereign
 * Border style and the legend's rule changes with it — which is the only way a
 * legend stays true as a map is restyled.
 */
export interface LegendEntry {
  id: UUID;
  /** Which part of the stylesheet `styleId` refers to, and how to draw it. */
  kind: 'symbol' | 'line' | 'fill';
  styleId: UUID;
  text: string;
  hidden: boolean;
}

export interface LegendSettings {
  enabled: boolean;
  title: string;
  position: FurniturePosition;
  /**
   * Rebuild the rows from what the map actually contains whenever it is drawn.
   * Editing a row turns this off, because the user's arrangement is then the
   * thing to preserve.
   */
  auto: boolean;
  entries: LegendEntry[];
}

export interface CompassSettings {
  enabled: boolean;
  style: 'star' | 'rose' | 'arrow';
  position: FurniturePosition;
  /** Diameter in output px, before the export's style scale. */
  size: number;
}

/** Collections that hold identified features; used by the undo system. */
export type FeatureCollectionKey = 'territories' | 'settlements' | 'linearFeatures' | 'labels';

/** The union of everything a `FeatureCollectionKey` can address. */
export type AnyFeature = Territory | Settlement | LinearFeature | MapLabel;

/** Handy alias for turf round-trips. */
export type GeoFeature<G extends Polygon | MultiPolygon | Point | LineString | MultiLineString> =
  Feature<G, Record<string, unknown>>;
